Build: change node version check to warning and move to nightly job

diff --git a/.github/workflows/nightly-stage-test-action.yml b/.github/workflows/nightly-stage-test-action.yml
--- a/.github/workflows/nightly-stage-test-action.yml
+++ b/.github/workflows/nightly-stage-test-action.yml
@@ -82,6 +82,32 @@ jobs:
           } >> .env 2>/dev/null
           echo "✅ Environment file created successfully"
 
+      - name: Compare .nvmrc files
+        id: compare-nvmrc
+        run: |
+          # Get both .nvmrc files
+          curl https://raw.githubusercontent.com/content-services/content-sources-backend/refs/heads/main/_playwright-tests/.nvmrc -o backend-nvmrc
+          backendNvmrc="backend-nvmrc"
+          frontendNvmrc=".nvmrc"
+
+          # Check if both files exist
+          if [ ! -f "$backendNvmrc" ]; then
+            echo "Error: $backendNvmrc does not exist."
+            exit 1
+          fi
+
+          if [ ! -f "$frontendNvmrc" ]; then
+            echo "Error: $frontendNvmrc does not exist."
+            exit 1
+          fi
+
+          # Compare the contents of the two files
+          if ! cmp -s "$backendNvmrc" "$frontendNvmrc"; then
+            echo "::warning::The .nvmrc files are not the same."
+          else
+            echo "The .nvmrc versions are the same!"
+          fi
+
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
